# weight settings
w_basepos: [500, 500, 1500, 300, 300, 100]
w_basevel: [10, 10, 100, 30, 30, 10]
w_legpos: [5, 5, 2.5]
w_legvel: [0.01, 0.01, 0.005]
w_foot: [0, 0, 500]
w_force: [0.001, 0.001, 0.001]
w_legacc: [1e-8, 1e-8, 1e-8]

# mpc settings
horizon: 50     # number of steps in the prediction horizon
timestep: 0.01  # timestep in the prediction horizon
max_iter: 1     # maximum number of iterations in ddp solver
num_threads: 8  # number of threads in ddp solver

# dynamic settings
friction: 0.8